### ISSUE TITLE
Goto statements backwards

### ISSUE THREAD

**Issue by burnout426** [usefulstuffs/ByeByeEdge-OneCMD#1]
Saw this project mentioned at <https://www.reddit.com/r/browsers/comments/1f7jsy7/comment/ll9ha0t/?utm_source=reddit&utm_medium=web2x&context=3>.

At <https://github.com/usefulstuffs/ByeByeEdge-OneCMD/blob/main/UninstallEdge.cmd#L51>, are those gotos backwards?

Shouldn't it be?:

```
if exist "%ProgramFiles%\Microsoft\Edge" goto uninstall64
if exist "%ProgramFiles(x86)%\Microsoft\Edge" goto uninstall32
```

**Comment by usefulstuffs** [comment]
No, as Edge on x64 systems installs in %ProgramFiles(x86)% while on x86 systems there's only %ProgramFiles%

**Comment by burnout426** [comment]
` Edge on x64 systems installs in %ProgramFiles(x86)%`

Ah, unexpected, but you're right.
